### ISSUE TITLE
Misspelled word issue.

### ISSUE THREAD

**Issue by khanhnb** [chrisjmccormick/inspect_word2vec#1]
Hi chrisjmccormick,

I want to map my vocab with Google's pre-trained model. But my vocab contains some misspelled words such as 'acknowledg'. Is there any way to find the suitable word in Google's pre-trained model so I can find acknowledg's represent? 

Thank you!

**Comment by chrisjmccormick** [comment]
You could try using the "edit distance" to find which word in Google's vocabulary most closely matches your input word. Check out [this question on stackoverflow](http://stackoverflow.com/questions/2460177/edit-distance-in-python), looks like it has what you'd need.

Also, if you get multiple close matches, and you want to try to map it to the _real_ word (e.g., "acknowledge"), you can use WordNet through NLTK to check if it's a real, correctly spelled word. I did this in another project [here](https://github.com/chrisjmccormick/word2vec_matlab/blob/master/model/filter_vocab.py).

**Comment by khanhnb** [comment]
I thought that gensim contains a method to do this job but It turns out that we have to do it ourselves. Thank you for the hints.

Thank you very much, chrisjmccormick!
