### ISSUE TITLE
Error while loading pre-trained model

### ISSUE THREAD

**Issue by avhirupc** [chrisjmccormick/inspect_word2vec#2]
I am having some problem while loading the pre-trained model you supplied
![capture](https://cloud.githubusercontent.com/assets/12384502/22883987/a6312894-f218-11e6-97db-afbbc184f628.PNG)

I am using python 3.5 64 bit

**Comment by chrisjmccormick** [comment]
That looks like the wrong binary? './enwiki_dbow/enwiki_dbow/doc2vec.bin'?

The file should be: GoogleNews-vectors-negative300.bin

But to your error specifically--string encoding is a tricky subject that I haven't mastered yet. Look around, though, and you'll find lots of help on the topic.

**Comment by avhirupc** [comment]
thanks. I tried it out with GoogleNews-vectors-negative300.bin it worked.Maybe there was some problem with the binary file I downloaded.
