### ISSUE TITLE
Word2vec for Sentences

### ISSUE THREAD

**Issue by avhirupc** [chrisjmccormick/inspect_word2vec#3]
how can I use this pre-trained model for sentence embeddings? 
examples: How can I convert "This is a pink flower with white sepal" into a vector 
Adding  word vectors doesn't give good results

**Comment by chrisjmccormick** [comment]
You can try averaging the word vectors (as opposed to just adding). Otherwise, check out doc2vec--it handles sentence embedding.

**Comment by avhirupc** [comment]
I tried using doc2vec.The infer vector in doc2vec has some errors.Any good code reference for doc2vec?
`import gensim
model = gensim.models.doc2vec.Doc2Vec.load_word2vec_format('GoogleNews-vectors-negative300/GoogleNews-vectors-negative300.bin', binary=True) 

vector=model.infer_vector(['the', 'cat', 'jumped'])`

Here's the error,
C:\Users\zc440z0ac\AppData\Local\Continuum\Anaconda3\lib\site-packages\gensim\ut
ils.py:855: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Traceback (most recent call last):
  File "doc2vectest.py", line 10, in <module>
    vector=model.infer_vector(['the', 'cat', 'jumped'])
  File "C:\Users\zc440z0ac\AppData\Local\Continuum\Anaconda3\lib\site-packages\g
ensim\models\doc2vec.py", line 741, in infer_vector
    doctag_vectors=doctag_vectors, doctag_locks=doctag_locks)
  File "gensim/models/doc2vec_inner.pyx", line 414, in gensim.models.doc2vec_inn
er.train_document_dm (./gensim/models/doc2vec_inner.c:5255)
    word_locks = model.syn0_lockf
AttributeError: 'Doc2Vec' object has no attribute 'syn0_lockf'

I would be really grateful .

**Comment by chrisjmccormick** [comment]
Interesting--I haven't tried using doc2vec yet, so I don't have any insight. Post an issue to gensim, though--they're pretty responsive over there.

**Comment by avhirupc** [comment]
Thanks man

**Comment by chrisjmccormick** [comment]
You're welcome!
