### ISSUE TITLE
Unknown Token

### ISSUE THREAD

**Issue by blester125** [chrisjmccormick/inspect_word2vec#5]
Do these word vectors contain a token like <unk> for unknown words? That seems like a good talking point in your inspection

**Comment by chrisjmccormick** [comment]
No, you can't learn a word vector for a word you know nothing about, so it simply can't support words that aren't in the dictionary. 

Maybe, though, you could find which word in the vocabulary which has the smallest edit distance to the input word? This could maybe handle small issues like misspellings.

**Comment by blester125** [comment]
For what it is worth you can learn an unknown word vector. For example:

 * You can average the X least common words and use that as the 'UNK' vector because an unseen word would probably be similar to the uncommon words. (This is done in the GloVe implementation from the Stanford NLP website)
 * You can average all the word vectors because an unknown word could be any word so the average of all words is probably better than a random guess. This average could also be weighted by frequency or something similar (but probably not because I would assume a unknown word is probably not similar to the super common words because it would be common)
 * You can have a frequency cut off in you vocabulary and then have words in your Word2Vec training set be 'UNK' which would learn a vector for words that are uncommon.

There are a lot of ways to handle an unknown word during the creation of word vectors that I think would help performance vs just picking a random vector and using that.

**Comment by chrisjmccormick** [comment]
Interesting ideas, thanks!
